spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: com
  datasource:
    #shujuyuan
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456qQ
    url: jdbc:mysql://localhost:3306/xian?useUnicode=true&characterEncoding=utf-8
  resources:
    static-locations:classpath:/static/**
  session:
    store-type: redis
    host: 127.0.0.1
    port: 6379
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
#    timeout: 0ms

#jiazai mybatis peizhiwenjian
#mybatis:
#  mapperas-locations: classpath:mapperas/*Mapper.xml
#  config-location: classpath:mapperas/config/sqlMapConfig.xml
#  type-aliases-package: com.xian.demo.entity
#  table:
#    auto: create
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888

# logger
logging:
  config: classpath:logback.xml
xian:
  reqUserKey: currentUser
  reqHeadKey: token