spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: com
  datasource:
    #shujuyuan
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456qQ
    url: jdbc:mysql://localhost:3306/xian?useUnicode=true&characterEncoding=utf-8
  resources:
    static-locations:classpath:/static/**
  session:
    store-type: redis
#    timeout: 2000ms
    host: 127.0.0.1
    port: 6379

#jiazai mybatis peizhiwenjian
#mybatis:
#  mapperas-locations: classpath:mapperas/*Mapper.xml
#  config-location: classpath:mapperas/config/sqlMapConfig.xml
#  type-aliases-package: com.xian.demo.entity
#  table:
#    auto: create

server:
  port: 8888

# logger
logging:
  config: classpath:logback.xml